# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/reunion',
                'doc_host': 'https://jm1021.github.io',
                'git_url': 'https://github.com/jm1021/reunion',
                'lib_path': 'reunion'},
  'syms': {'reunion.core': {'reunion.core.foo': ('core.html#foo', 'reunion/core.py')}}}
